# Generated by Django 5.2.8 on 2026-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
