# Generated by Django 5.2.8 on 2026-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('friends', 'Friends Only'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
