# Generated by Django 5.2.8 on 2026-05-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_commentdislike_postdislike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentDislike',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
