# Generated by Django 5.2.8 on 2026-04-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
